name: Build and Push ChatTTS-ui Docker Images

on:
  workflow_dispatch:
  schedule:
    # 每月3号凌晨0点运行
    - cron: '0 0 3 * *'

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USER }}/chattts-ui

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          repository: 'jianchang512/ChatTTS-ui'
          fetch-depth: 0
          
      - name: 获取最新tag
        id: latest_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) || echo "latest")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest tag: $LATEST_TAG"
          
      - name: 检出最新tag
        run: |
          if [ "$LATEST_TAG" != "latest" ]; then
            git checkout $LATEST_TAG
            echo "已检出版本: $LATEST_TAG"
          else
            echo "未找到tag，使用最新主分支"
          fi

      - name: 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
            
      # 检出自定义Dockerfile仓库
      - name: 检出自定义Dockerfile仓库
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
          path: 'custom-dockerfile'
          fetch-depth: 0
          
      # 构建自定义GPU版本
      - name: 构建并推送自定义GPU版Docker镜像
        uses: docker/build-push-action@v5
        with:
          file: custom-dockerfile/Dockerfile.chattts-ui-gpu
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:custom-gpu-latest
            ${{ env.DOCKER_IMAGE }}:custom-gpu-${{ env.LATEST_TAG }}
