name: Build and Push CosyVoice-Pre Docker Image

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USER }}/cosyvoice

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          repository: 'hewenyu/CosyVoice-Pre'
          fetch-depth: 0
          
      - name: 获取最新tag
        id: latest_commit
        run: |
          LATEST_COMMIT=$(git rev-parse HEAD)
          echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV
          echo "Latest commit: $LATEST_COMMIT"
          
      - name: 检出最新commit
        run: |
          git checkout $LATEST_COMMIT
          echo "已检出版本: $LATEST_COMMIT"

      - name: 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:pre
            ${{ env.DOCKER_IMAGE }}:pre-${{ env.LATEST_COMMIT }}
