name: Build and Push Clash Docker Image (Local)

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/build-clash-local.yml'
  workflow_dispatch:

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USER }}/clash

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 获取时间戳
        id: timestamp
        run: echo "timestamp=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:stotik
            ${{ env.DOCKER_IMAGE }}:stotik-v1.18.0
            ${{ env.DOCKER_IMAGE }}:${{ steps.timestamp.outputs.timestamp }}

      - name: 输出镜像信息
        run: |
          echo "镜像已成功推送到 Docker Hub:"
          echo "- ${{ env.DOCKER_IMAGE }}:stotik"
          echo "- ${{ env.DOCKER_IMAGE }}:stotik-v1.18.0"
          echo "- ${{ env.DOCKER_IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
