name: Build and Push F5-TTS Docker Image

on:
  workflow_dispatch:
  schedule:
    # 每月2号凌晨0点运行
    - cron: '0 0 2 * *'

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USER }}/f5-tts

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKERHUB
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          repository: 'SWivid/F5-TTS'
          fetch-depth: 0
          
      - name: 获取最新tag
        id: latest_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest tag: $LATEST_TAG"
          
      - name: 检出最新tag
        run: |
          git checkout $LATEST_TAG
          echo "已检出版本: $LATEST_TAG"

      - name: 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ env.LATEST_TAG }}
