name: Build and Push CosyVoice Docker Images

on:
  workflow_dispatch:
  # schedule:
  #   # 每月2号凌晨0点运行
  #   - cron: '0 0 2 * *'

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USER }}/cosyvoice

jobs:
  build-and-push:
    runs-on: self-hosted
    environment: DOCKERHUB
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 时间作为版本号
        id: version
        run: |
          echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "Version: $VERSION"

      # 构建自定义GPU版本
      - name: 构建并推送自定义GPU版Docker镜像
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.cosyvoice-ui-gpu
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}

      - name: docker logout
        run: |
          docker logout

      - name: Prune unused Docker data
        run: |
          docker system prune -af --volumes

      
